### ISSUE TITLE
Gnome Extensions help

### ISSUE THREAD

**Issue by moritz-t-w** [gjsify/types#2]
I'm writing a GNOME shell extension and I was wondering if and how I could use this package to get type hints when I'm forced to import modules from like this, according to the [guide](https://gjs.guide/extensions/development/preferences.html#prefs-js):
```js
import Gio from 'gi://Gio';
import Adw from 'gi://Adw';
```

**Comment by schnz** [comment]
Hey @moritz-t-w ,

I suppose there are multiple possible ways on how to achieve that. It really depends on your project setup.

Two possibilities that come to mind:

--- 
1) `tsconfig.json` (using [typeRoots](https://www.typescriptlang.org/tsconfig#typeRoots))

```json
{
  "compilerOptions": {
    "typeRoots": ["./node_modules/@girs"],
  }
}
```

---

2) Using an [ambient declaration `d.ts` file](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html)

`name-of-your-choice.d.ts`

```ts
/// <reference path="./node_modules/@girs/gjs/dom.d.ts" />
/// <reference path="./node_modules/@girs/gnome-shell/dist/index-ambient.d.ts" />
```

**Comment by moritz-t-w** [comment]
Thanks for the quick reply! I'm just using js so tsconfig wouldn't do anything, right?

**Comment by moritz-t-w** [comment]
> 2. Using an [ambient declaration d.ts file](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html)
Oh and the comments would just go above the imports as doc comments?

**Comment by schnz** [comment]
> Oh and the comments would just go above the imports as doc comments?

These _comments_ have a special semantic in Typescript (see https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html).

> Thanks for the quick reply! I'm just using js so tsconfig wouldn't do anything, right?

If you are using plain JavaScript I am unaware of a solution that would provide type hints.

**Comment by moritz-t-w** [comment]
Yeah I misread, didn't see they were meant to go in the d.ts file

**Comment by moritz-t-w** [comment]
> If you are using plain JavaScript I am unaware of a solution that would provide type hints.

Aww man. And there's no vscode extension either. Guess I'm on my own

**Comment by schnz** [comment]
I can only recommend using TypeScript. It requires you to introduce a build step, but that really boils down to an `npx tsc` command. You could check https://github.com/gTile/gTile for a reference.

**Comment by moritz-t-w** [comment]
Yeah ik but I've already gone too far without it, should have made the decision earlier. Now I don't have time to switch.

**Comment by schnz** [comment]
> Yeah ik but I've already gone too far without it, should have made the decision earlier. Now I don't have time to switch.

Whatever is right for you. IMO it's never too late. Being a strict superset of ECMAScript  you can always transition to TypeScript. It doesn't really depend on the size/progress of your project (except for renaming existing `.js` files to `.ts` probably). In my experience, the time it takes to setup the project pays off in the end.

**Comment by moritz-t-w** [comment]
Right, I forgot it's actually a superset.

**Comment by moritz-t-w** [comment]
Cheers thanks!
