### ISSUE TITLE
`gi://Soup` not found

### ISSUE THREAD

**Issue by moritz-t-w** [gjsify/types#3]
After installing `@girs/soup-3.0`:
https://github.com/moritz-t-w/TL_Time_Tracker/blob/69e942295d1aaaf3ca26ee33ee9cd8f377060730/package.json#L17
```json
"@girs/soup-3.0": "^3.4.4-3.2.6",
```
I can't import it:
```ts
import Soup from 'gi://Soup';
```
> Cannot find module 'gi://Soup' or its corresponding type declarations. `ts(2307)`

I can however import, for example, `GLib` in this exact way and it works:  
https://github.com/moritz-t-w/TL_Time_Tracker/blob/69e942295d1aaaf3ca26ee33ee9cd8f377060730/src/HTTP.ts#L2
```ts
import GLib from 'gi://GLib';
```
I copied a lot of my configuration from [gTile](https://github.com/gTile/gTile/). However they don't have `Soup` so I added that myself.

**Comment by moritz-t-w** [comment]
Currently I am importing it like this:
https://github.com/moritz-t-w/TL_Time_Tracker/blob/69e942295d1aaaf3ca26ee33ee9cd8f377060730/src/HTTP.ts#L1
```ts
import Soup from '@girs/soup-3.0';
```
And that works for development but gjs needs `gi://` as far as I can tell

**Comment by schnz** [comment]
Glad to see that you decided to switch to TypeScript :+1: .

Most imports are recursive dependencies of the [`gnome-shell`](https://github.com/gjsify/gnome-shell/blob/2ae398b65cda685d444de08e0d25463b14bc8056/packages/gnome-shell/package.json#L885-L909) package which already imports the ambient declaration files of all the dependencies. Thus it was sufficient to reference the gnome-shell ambient declaration file

`gnome-shell.d.ts`
```
/// <reference path="./node_modules/@girs/gnome-shell/dist/index-ambient.d.ts" />
```

If you rely on further packages, you have to reference the ambient declaration file explicitly
```patch
diff --git a/gnome-shell.d.ts b/gnome-shell.d.ts
index db155b5..5297b32 100644
--- a/gnome-shell.d.ts
+++ b/gnome-shell.d.ts
@@ -1,5 +1,6 @@
 /// <reference path="./node_modules/@girs/gjs/dom.d.ts" />
 /// <reference path="./node_modules/@girs/gnome-shell/dist/index-ambient.d.ts" />
+/// <reference path="./node_modules/@girs/soup-3.0/soup-3.0-ambient.d.ts" />

 interface ImportMeta {
        url: string;
```

**Comment by moritz-t-w** [comment]
That worked, thanks! I like the idea of using `diff` to clarify changes btw
