### ISSUE TITLE
Where's @girs/gio-2.0 2.78-3.2.7?

### ISSUE THREAD

**Issue by swsnr** [gjsify/types#7]
I'm a bit confused about the versions currently published on npm.  Taking `@girs/gio` as example:

![grafik](https://github.com/gjsify/types/assets/224922/e9ff7058-6844-4b28-8635-37ee94d3f0ad)

We have 2.77-3.2.8, which I presume refers to GLib 2.77 types generated with ts-for-gir 3.2.8, and we have 2.78-3.2.7 which I understand to contain GLib 2.78 types generated with ts-for-gir 3.2.7.

So we have newer GLib types generated with an older ts-for-gir version, and older GLib types generated with newer ts-for-gir version?

As similar situation occurs e.g. for Soup (3.4.4-3.2.7 versus 3.4.2-3.2.8).  

This is pretty confusing, and it makes yarn install duplicate versions which terribly confuses typescript, see https://github.com/swsnr/gnome-shell-extension-picture-of-the-day/pull/61 and the build failure in https://github.com/swsnr/gnome-shell-extension-picture-of-the-day/actions/runs/8107187764/job/22158290568?pr=61

**Comment by JumpLink** [comment]
@swsnr This must have been an oversight, I suspect it's because I copied the gir files into the repository and the newer ones were ignored on my system. I'll try to fix this as soon as I have time. The cleanest solution would probably be to automatically select the newer one if several Gir files with the same name are found or ask which one should be used

**Comment by JumpLink** [comment]
@swsnr should be fixed now, can you confirm that?

**Comment by swsnr** [comment]
Oh, you're faster than I can even respond.  I'll test this, but might take till next weekend 🙂

**Comment by JumpLink** [comment]
@swsnr looks good, right?

**Comment by swsnr** [comment]
@JumpLink Thanks for pinging me. I had completely forgotten about this affair, but sat down and tried it.

It's better, but I still get duplicate versions of gir typings which confuse typescript.  I guess that's because gnome-shell [still depends on the `*-3.2.7` versions](https://github.com/gjsify/gnome-shell/blob/470f106b7714b51b599f0a3b9d82215d96815f34/packages/gnome-shell/package.json#L908), and this kinda confuses yarn.

But to be honest, my understanding on how yarn resolves package versions—specifically these intricate two-part versions the gjs typings use—is rather limited, so I might be doing something wrong 🤔

**Comment by swsnr** [comment]
@JumpLink I tested with `pnpm` and had no issues there; it looks as if `yarn` doesn't really deduplicate packages in the tree 🤷🏿 

Sorry for the noise, and thanks for fixing this.
